### ISSUE TITLE
Customers losing session

### ISSUE THREAD

**Issue by rafaelpatro** [colinmollenhour/Cm_RedisSession#155]
Hi guys

Occasionally some customers are losing the session. But my local test works great and many customers can buy without problems.

So I don't know how to investigate the problem. Any tip?
Anyone with same problem?

_p.s. Some time ago I've installed that Plumrocket AMP extension and it was great for performance and SEO. My tests with the extension are Ok too. Could it be related with?_

**Comment by colinmollenhour** [comment]
There are all sorts of possible reasons and it is not at all easy to debug.. However, we've applied some fixes for session validation and the "secure cookie" renewal over at OpenMage/magento-lts project so you might consider trying it out.

**Comment by rafaelpatro** [comment]
Yep! Thanks
First reason was my redis limit that achieves 2G. Solved increasing to 4GB. I have so much RAM. How can I set to unlimited?

But I'm facing the same issue below too. And LTS was the best response.
https://magento.stackexchange.com/questions/167616/session-validation-failure-in-magento-1-ee-v-1-14-3-x-and-ce-1-9-3-x

**Comment by rafaelpatro** [comment]
So there is something wrong with my store. Could it grow 1GB in one day?
![image](https://user-images.githubusercontent.com/13813964/46703766-70d5ed80-cbfe-11e8-8a2d-13311fa423b1.png)

**Comment by colinmollenhour** [comment]
If your low limit was causing a lot of key evictions then I would expect to see a spike when the limit is raised.

Note, I strongly recommend running separate redis instances for cache vs session and also FPC vs core cache. With each role having it's own memory limit you reduce risk of one running rampant and causing major issues for the other. E.g. for core cache you want this to never experience evictions and it shouldn't need to since it should be pretty small. FPC and sessions could both use a lot of memory but if they have separate limits then at least they can't negatively impact each other. It is really easy to setup multiple redis instances with Docker. E.g. here is a docker-compose.yml file:

```
version: '3'
services:
  redis-cache:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --maxmemory 512mb --maxmemory-policy volatile-lru --maxmemory-samples 3
    restart: always
    volumes:
      - redis-cache:/data

  redis-session:
    image: redis
    ports:
      - "127.0.0.1:6380:6379"
    command: redis-server --maxmemory 1500mb --maxmemory-policy volatile-lru --maxmemory-samples 3
    restart: always
    volumes:
      - redis-session:/data

  redis-fpc:
    image: redis
    ports:
      - "127.0.0.1:6381:6379"
    command: redis-server --maxmemory 1024mb --maxmemory-policy volatile-lru --maxmemory-samples 3
    restart: always
    volumes:
      - redis-fpc:/data

volumes:
  redis-cache:
  redis-session:
  redis-fpc:
```

Save that to `docker-compose.yml` and then run `docker-compose up` and access each instance at 127.0.0.1 ports 6379, 6380 and 6381.
